[package]
name = "numoji/puppetplugin"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
StudioComponents = "sircfenner/studiocomponents@1.0.0"
Janitor = "howmanysmall/janitor@1.16.0"
